# Generated by Django 4.1.5 on 2023-06-01 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regForm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registereduser',
            name='dob',
            field=models.DateField(),
        ),
    ]
